-   repo: https://github.com/reyoung/mirrors-yapf.git
    sha: v0.13.2
    hooks:
    - id: yapf
      files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$  # Bazel BUILD files follow Python syntax.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
        files: \.md$
    -   id: trailing-whitespace
        files: \.md$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.1
    hooks:
    -   id: forbid-crlf
        files: \.md$
    -   id: remove-crlf
        files: \.md$
    -   id: forbid-tabs
        files: \.md$
    -   id: remove-tabs
        files: \.md$
- repo: local
  hooks:
    -  id: convert-markdown-into-html
       name: convert-markdown-into-html
       description: Convert README.md into index.html and README.en.md into index.en.html
       entry: python pre-commit-hooks/convert_markdown_into_html.py
       language: system
       files: \.md$
- repo: local
  hooks:
    -  id: convert-markdown-into-ipynb
       name: convert-markdown-into-ipynb
       description: Convert README.md into README.ipynb and README.en.md into README.en.ipynb
       entry: ./pre-commit-hooks/convert_markdown_into_ipynb.sh
       language: system
       files: \.md$
